script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
branches:
  only:
    - master
    - folsom
    - essex
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
env:
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION="~> 3.0"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.7"
notifications:
  email: false
